### ISSUE TITLE
File name color is the same as the highlighted color in light theme

### ISSUE THREAD

**Issue by keck-in-space** [tmpr/populus#1]
I'm using v0.2.0 of the theme and I've noticed that in the File Explorer, if I select a file that has pending edits in Git and then begin editing the file again, the file name in the File Explorer window is unreadable because the highlight color is the same as the file edited color. This only occurs in the light mode and if I have modified the file.

This is the color I believe, but I'm not sure how it is being used for the text color and text selection background color.

```json
"gitDecoration.modifiedResourceForeground": "#48b8c7"
```

Example

![image](https://user-images.githubusercontent.com/32853381/116591496-e2750480-a8ec-11eb-975a-281ab64b75ea.png)

![image](https://user-images.githubusercontent.com/32853381/116591519-e7d24f00-a8ec-11eb-890f-384fed64093e.png)

**Comment by tmpr** [comment]
Hey key-in-space!

This should be fixed by now! Thank you a lot for noticing! :)

**Comment by keck-in-space** [comment]
Looks good! Fixed in v0.2.1. Thank you.
