### ISSUE TITLE
Comment indicator should be greyed out in dark mode

### ISSUE THREAD

**Issue by keck-in-space** [tmpr/populus#2]
The comment indicator in Python should be greyed out. With dark mode in Populus, the `#` character is the same color as normal code. It should be the same color as the comment itself.

**Comment by tmpr** [comment]
Thank you for issuing this! 💟 
Should be fixed in 0.2.2.

**Comment by keck-in-space** [comment]
I just installed v0.2.2 and this is fixed! Great work! Thanks.
